#!/usr/bin/env bash

source functions.sh

! provision_test_environment && bash_on_error && exit 1

info "running ssh-socks-proxy provision script with .env file generated by the test environment provision script"
! upv . provision && bash_on_error && exit 1
! docker_build_run "ssh-socks-proxy" "${UPV_WORKSPACE}" "-d --network host --env-file ${UPV_WORKSPACE}/.env" "2" && bash_on_error && exit 1
docker_wait "ssh-socks-proxy" 10 || exit 1
ssh_socks_proxy_test
